preprocess:
  split: 0.2
  seed: 42
train:
    epochs: 15
    lr: 0.001
    batch_size: 32
    num_classes: 10
evaluate:
    metrics:
    - accuracy
    - f1
    - precision
    - recall
    num_classes: 10